DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE repositories (
  repo_id INTEGER PRIMARY KEY AUTOINCREMENT,
  FOREIGN KEY(product_id) REFERENCES products(product_id)
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE products (
  poduct_id INTEGER PRIMARY KEY AUTOINCREMENT=10000,
  name TEXT NOT NULL,
  body TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
)

CREATE TABLE contacts (
  contact_id INTEGER PRIMARY KEY AUTOINCREMENT,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  chat_username TEXT,
  location TEXT,
  role TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE product_contacts (
  product_contact_id INTEGER PRIMARY KEY AUTOINCREMENT,
  FOREIGN KEY(product_id) REFERENCES products(product_id)
  FOREIGN KEY(contact_id) REFERENCES contacts(contact_id)
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

